### ISSUE TITLE
meshcli does not start

### ISSUE THREAD

**Issue by rimhagen** [SilvairGit/python-bluetooth-mesh#119] opened 2021-05-21 09:04 UTC
I'd like to try out this package but running meshcli without arguments gives me a runtime error. 

```
(.venv) nisse@machine:~/Workspace/PythonBluetoothMesh$ meshcli
Traceback (most recent call last):
  File "/home/nisse/Workspace/PythonBluetoothMesh/.venv/bin/meshcli", line 8, in <module>
    sys.exit(main())
  File "/home/nisse/Workspace/PythonBluetoothMesh/.venv/lib/python3.7/site-packages/bluetooth_mesh/apps/meshcli.py", line 1752, in main
    loop.run_until_complete(mesh_cli.run(arguments.get("<command>")))
  File "/home/nisse/.pyenv/versions/3.7.10/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/nisse/Workspace/PythonBluetoothMesh/.venv/lib/python3.7/site-packages/bluetooth_mesh/apps/meshcli.py", line 1653, in run
    self.address, self.network, self.iv_index = await self.get_network()
  File "/home/nisse/Workspace/PythonBluetoothMesh/.venv/lib/python3.7/site-packages/bluetooth_mesh/apps/meshcli.py", line 1619, in get_network
    get_address, self.arguments["--env"], self.arguments["--partner"]
TypeError: get_network() takes 1 positional argument but 4 were given
```

Also, it would be helpful if you could provide a sample application. For instance, an application which imports a mesh node and adds a Generic OnOff Server model.

Thanks!

bluetooth-mesh 0.7.2
bluez 5.56
ell 0.40

**Comment by michallowasrzechonek-silvair** [comment] 2021-06-03 19:57
The issue is related to https://github.com/SilvairGit/python-bluetooth-mesh/issues/47.

Essentially, this package *doesn't* implement a local provisioning database. Which is a damn shame :(

**Comment by michallowasrzechonek-silvair** [comment] 2021-06-03 19:58
A separate problem is the confusing error message, introduced by some recent internal API changes. This one should be easy to fix, to at least let users know what's going on.

**Comment by michallowasrzechonek-silvair** [comment] 2021-06-16 11:48
Error message has been fixed in https://github.com/SilvairGit/python-bluetooth-mesh/commit/158c70258e37094a54dfe83bfbe54152e27dee73, but the underlying lack of local database remains.

**Closed by michallowasrzechonek-silvair** 2021-06-16 11:48 UTC
